name: Disable Copilot PR Suggestions

# triggers on any branch push
on:
  push:

permissions:
  administration: write  # needed to update repo settings via GraphQL

jobs:
  disable-copilot-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Disable Copilot pull-request suggestions
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const core = require('@actions/core');

            // fetch this repository’s GraphQL node ID
            let repoId;
            try {
              const { data } = await github.graphql(
                `
                query RepoID($owner:String!, $name:String!) {
                  repository(owner:$owner, name:$name) { id }
                }
                `,
                { owner: context.repo.owner, name: context.repo.repo }
              );
              repoId = data.repository.id;
            } catch (error) {
              core.setFailed(`Failed to fetch repository ID: ${error.message}`);
              return;
            }

            // run the mutation to turn off copilotPullRequestsEnabled
            try {
              await github.graphql(
                `
                mutation DisableCopilotPRs($id:ID!) {
                  updateRepository(
                    input: { repositoryId: $id, copilotPullRequestsEnabled: false }
                  ) {
                    repository { nameWithOwner }
                  }
                }
                `,
                { id: repoId }
              );
            } catch (error) {
              core.setFailed(`Failed to disable Copilot PR suggestions: ${error.message}`);
              return;
            }

            console.log(`✅ Copilot PRs disabled for ${context.repo.owner}/${context.repo.repo}`);
