name: Disable Copilot PR Suggestions

# trigger on every branch push
on:
  push:

# GITHUB_TOKEN defaults will allow repository mutations
# (no explicit permissions: administration needed, and
# ‘administration’ is not currently supported by the parser)

jobs:
  disable-copilot-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Disable Copilot pull-request suggestions
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // fetch this repository’s GraphQL node ID
            let repoId;
            try {
              const { repository } = await github.graphql(
                `
                query RepoID($owner:String!, $name:String!) {
                  repository(owner:$owner, name:$name) { id }
                }
                `,
                { owner: context.repo.owner, name: context.repo.repo }
              );
              repoId = repository.id;
            } catch (error) {
              core.setFailed(`Failed to fetch repository ID: ${error.message}`);
              return;
            }

            // run the mutation to turn off copilotPullRequestsEnabled
            try {
              await github.graphql(
                `
                mutation DisableCopilotPRs($id:ID!) {
                  updateRepository(
                    input: { repositoryId: $id, copilotPullRequestsEnabled: false }
                  ) {
                    repository { nameWithOwner }
                  }
                }
                `,
                { id: repoId }
              );
            } catch (error) {
              core.setFailed(`Failed to disable Copilot PR suggestions: ${error.message}`);
              return;
            }

            console.log(`✅ Copilot PRs disabled for ${context.repo.owner}/${context.repo.repo}`);
